version: "3"

services:
  devnet:
    image: shardlabs/starknet-devnet:latest
    command:
    - "--host=0.0.0.0"
    - "--port=5050"
    - "--disable-rpc-request-validation"
    ports:
    - 5050:5050

  apibara:
    image: quay.io/apibara/starknet:5e284618b2a1eea49aa04cb04d452ec48b3ffb99
    ports:
    - 7171:7171
    depends_on:
    - devnet
    restart: always
    command:
    - "start"
    - "--data=/data"
    - "--rpc=http://devnet:5050/rpc"
    environment:
    - OTEL_SDK_DISABLED=true # disable tracing/metrics
    volumes:
    - apibara-data:/data

  mongo-goerli:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${GOERLI_DB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${GOERLI_DB_PASSWORD}
    ports:
    - 27017:27017
    volumes:
    - mongo-data:/data/goerli/db

  mongo-devnet:
    image: mongo:latest
    restart: always
    command: mongod --port 27018
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DEVNET_DB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${DEVNET_DB_PASSWORD}
    ports:
    - 27018:27018
    volumes:
    - mongo-data:/data/devnet/db

  indexer-goerli:
    image: starknetdev/loot-survivor-indexer:latest
    restart: always
    command:
    - start
    - --mongo-url
    - "mongodb://${GOERLI_DB_USERNAME}:${GOERLI_DB_PASSWORD}@mongo-goerli:27017"
    - --network
    - "goerli"
    - --adventurer
    - "0x035d755a23ec72df90819f584d9a1849bbc21fa77f96d25e03f1736883895248"
    - --beast
    - "0x000f4dbfe5d15792aa91025e42ee1d74c22bdeb1eef0b9bc19a37216377290c1"
    - --loot
    - "0x065669e15c8f1a7f17b7062e4eb1b709b922b931b93c59577f1848a85c30ab1f"
    - --start_block
    - "796600"
    environment:
      PYTHONUNBUFFERED: "1"
    links:
    - mongo-goerli

  indexer-devnet:
    image: starknetdev/loot-survivor-indexer:latest
    restart: always
    command:
    - start
    - --mongo-url
    - "mongodb://${DEVNET_DB_USERNAME}:${DEVNET_DB_PASSWORD}@mongo-devnet:27018"
    - --network
    - "devnet"
    - --adventurer
    - "0x07a6771c44602b93e8375610f886cefde0e3752073a5761b0fe2566281debf8e"
    - --beast
    - "0x03b2879fae55706b2412c7798570877b0e42712f7010910bb7c92912b0c6c7f3"
    - --loot
    - "0x04fd9fd16370c0dd2c562cb7aa2d6b973142da85c0cfb740ea69841009e98380"
    - --start_block
    - "30"
    environment:
      PYTHONUNBUFFERED: "1"
    links:
    - mongo-devnet

  graphql:
    image: starknetdev/loot-survivor-indexer:latest
    restart: always
    command:
    - graphql
    - --mongo_goerli
    - "mongodb://${GOERLI_DB_USERNAME}:${GOERLI_DB_PASSWORD}@mongo-goerli:27017"
    - --mongo_devnet
    - "mongodb://${DEVNET_DB_USERNAME}:${DEVNET_DB_PASSWORD}@mongo-devnet:27018"
    - --port
    - "8080"
    environment:
      PYTHONUNBUFFERED: "1"
    ports:
      - 8080:8080
    links:
    - mongo-goerli
    - mongo-devnet

volumes:
  mongo-data:
  apibara-data:
